services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ludu_db
      POSTGRES_USER: ludu_user
      POSTGRES_PASSWORD: ludu_pwd
    restart: unless-stopped

  api:
    container_name: ludu-api
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      WAIT_HOSTS: db:5432
    ports:
      - 8000:8000
  
  client:
    container_name: ludu-client
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - client-dist:/app/dist
    ports:
      - 8080:8080
  
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - client-dist:/usr/share/nginx/html
    command: >
      /bin/sh -c "echo 'Frontend is now accessible at http://localhost:8080' && nginx -g 'daemon off;'"
    depends_on:
      client:
        condition: service_completed_successfully
    ports:
      - '8080:80'

volumes:
  client-dist:
