services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ludu_db
      POSTGRES_USER: ludu_user
      POSTGRES_PASSWORD: ludu_pwd
    ports:
      - '5432:5432'
    restart: unless-stopped